// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlEDUcNxCx6uXdcpXBjKugJW3Jv6E-rrw',
    appId: '1:395643703227:web:360f91f90e92553ad13e9e',
    messagingSenderId: '395643703227',
    projectId: 'acadexa-aebed',
    authDomain: 'acadexa-aebed.firebaseapp.com',
    storageBucket: 'acadexa-aebed.firebasestorage.app',
    measurementId: 'G-JYJ6R7GJJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_QcZpBLF9oYZkKFy9f9RoZIyLRfw0iAE',
    appId: '1:395643703227:android:a9aa004640b0ce3ed13e9e',
    messagingSenderId: '395643703227',
    projectId: 'acadexa-aebed',
    storageBucket: 'acadexa-aebed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB0wf9cdKjau2DUbJh9RB0Ohdf0_9h_Bw',
    appId: '1:395643703227:ios:c9f25f53111f4a17d13e9e',
    messagingSenderId: '395643703227',
    projectId: 'acadexa-aebed',
    storageBucket: 'acadexa-aebed.firebasestorage.app',
    iosClientId: '395643703227-gj2boa368i6dojs9eb08l9p8h2fe23bc.apps.googleusercontent.com',
    iosBundleId: 'com.example.acadexa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB0wf9cdKjau2DUbJh9RB0Ohdf0_9h_Bw',
    appId: '1:395643703227:ios:c9f25f53111f4a17d13e9e',
    messagingSenderId: '395643703227',
    projectId: 'acadexa-aebed',
    storageBucket: 'acadexa-aebed.firebasestorage.app',
    iosClientId: '395643703227-gj2boa368i6dojs9eb08l9p8h2fe23bc.apps.googleusercontent.com',
    iosBundleId: 'com.example.acadexa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlEDUcNxCx6uXdcpXBjKugJW3Jv6E-rrw',
    appId: '1:395643703227:web:e0169548eab4af1ad13e9e',
    messagingSenderId: '395643703227',
    projectId: 'acadexa-aebed',
    authDomain: 'acadexa-aebed.firebaseapp.com',
    storageBucket: 'acadexa-aebed.firebasestorage.app',
    measurementId: 'G-TB81CZ918G',
  );
}
